### PR TITLE
Day 8 never loaded so I just made another file to count for it

### PR DESCRIPTION
**Pull request by Lito-Frito**

### CODE REVIEW

**Comment by Lito-Frito** [comment]
I did do work though

**Comment by dmadisetti** [comment]
Have you been following the github pages? https://baltimoreblacktechies.github.io/100daysOfCode-2021/Castillo/

I wonder how 8.5 will be ordered, I guess we'll see

**Comment by Lito-Frito** [comment]
It didin't take haha. Sorry for all the hassle. I need to do Aaron's Git bootcamp. 

When I clicked that link, it seems day 8 did pull through (pardon, I only checked the tracker). Would you rather I delete 8.5 or just create a Day 9 going forward?

**Comment by dmadisetti** [comment]
It did take

The image gets stuck in cache so it takes a second to propagate.

 8.5 is listed before 8 in the link, but that's fine

**Comment by dmadisetti** [comment]
Try hard refreshing if the change still doesn't show up

**Comment by Lito-Frito** [comment]
Success! Thank you!!!

**Pull request merged**
