### PR TITLE
Day6

### PR DESCRIPTION
**Pull request by Lito-Frito**

### CODE REVIEW

**Comment by Lito-Frito** [comment]
This is actually for Day 6 and 7. Forgot to push yesterday

**Comment by dmadisetti** [comment]
Hey Carlos, everyone else's folders are deleted. Can you create a PR with just your changes?

**Comment by Lito-Frito** [comment]
Sure thing!

**Comment by Lito-Frito** [comment]
Fixed

**Comment by dmadisetti** [comment]
I squashed and merged because the file deletions counted as deletions in the got tree and would have stripped their history.

So there's a chance this won't show up on the tracker because of this- but it should retrigger the process. At least we'll see if your gravatar worked

**Comment by Lito-Frito** [comment]
Awesome, thank you!

**Pull request merged**
